name: React CD - AWS S3

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.17.0]
    
    steps:
      - name: Setup repository access for job
        uses: actions/checkout@v1

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_VITE_API_HOST: https://tibas-api.herokuapp.com/
          file_name: .env
          fail_on_empty: true

      - name: Install packages
        run: yarn
      
      - name: Build app
        run: yarn build
      
      # - name: Run tests
      #  run: npm test 
      
      - name: AWS S3 Sync
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'sa-east-1'
          SOURCE_DIR: 'dist'